---
title: "Report of SpAnova"
subtitle: "Geostatistical Approach"
output: html_document
params:
  tab: NA
  modelVariofit: NA
  modelVariog: NA
  table: NA
  semiPar: NA
  CorF: NA
  McomP: NA
  McompName: NA
  modelGeo: NA
---

## Semivariogram
Correlation function: `r params$CorF`.

```{r, echo = FALSE, fig.align = 'center'}
plot(params$modelVariog)
lines(params$modelVariofit, col = 1)
```

## Semivariogram Parameter Estimates
```{r, echo = FALSE}
knitr::kable(params$semiPar)
```

## Analysis of Variance
```{r, echo = FALSE}
knitr::kable(params$tab)
```

## Checking the Residuals
```{r, echo = FALSE}
res <- params$modelGeo$residuals
par(mfrow = c(1,2))
hist(res, xlab = "Residuals", main = "", freq = FALSE)
lines(density(res))
qqnorm(res)
qqline(res)
```

```{r, echo = FALSE}
res <- params$modelGeo$residuals
plot(res, ylab = "Residuals")
```

\newpage

```{r, echo = FALSE}
knitr::kable(params$table)
```

```{r, echo = FALSE}
  if (params$table$P.value[1] < 0.05) {
    textRes <- "According to Shapiro-Wilk normality test at 5% of significance, residuals cannot be considered normal."
  }else {
    textRes <- "According to Shapiro-Wilk normality test at 5% of significance, residuals can be considered normal."
  }
```

```{r, echo = FALSE}
  if (params$table$P.value[2] < 0.05) {
    textRes2 <- "According to Moran I test at 5% of significance, there is spatial correlation among the residuals."
  }else {
    textRes2 <- "According to Moran I test at 5% of significance, there is no spatial correlation among the residuals."
  }
```

`r textRes`   

`r textRes2`    

## Multiple Comparison Procedure

Procedure: `r params$McompName`

```{r, echo = FALSE}
knitr::kable(params$McomP)
```

Treatments with the same letter are not significantly different at 5% of significance.


